env:
- ZMQ="git://github.com/zeromq/zeromq4-1.git -b v4.1.2" SODIUM="git://github.com/jedisct1/libsodium.git -b 1.0.3"
before_install:
- sudo apt-get install uuid-dev
- '[ -z "$SODIUM" ] || git clone --depth 1 $SODIUM libsodium'
- '[ -z "$SODIUM" ] || cd libsodium'
- '[ -z "$SODIUM" ] || ./autogen.sh'
- '[ -z "$SODIUM" ] || ./configure'
- '[ -z "$SODIUM" ] || make'
- '[ -z "$SODIUM" ] || sudo make install'
- '[ -z "$SODIUM" ] || cd ..'
- git clone --depth 1 $ZMQ zmqlib
- cd zmqlib
- ./autogen.sh
- ./configure
- make
- sudo make install
- sudo /sbin/ldconfig
- cd ..
language: node_js
node_js:
- "4.2"
- "5.5"
script: travis_retry npm test
